name: olivier
favicon: null
layout_spectrum: 0.47162
typography_spectrum: 0.85845
title: Olivier Tilmant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9cc6ee'
    - '#ff7d2f'
    - '#c4412f'
    - '#998fc1'
    - '#685888'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
