name: olivier
favicon: null
layout_spectrum: 0.5240199223626405
typography_spectrum: 0.5211363334674388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8171529686078429
  lightness: 0.7202489839401096
  saturation: 0.2713225439656526
  rhythmicContrast: 0.9677557642571628
purpose: []
